const data = [
    { clasificacion: "VARIABLES DE RIESGO </br> Este criterio, pretender analizar el RIESGO del ente, entre más cercano es la ponderacion a 50 puntos, menor es el riesgo del ente con respecto a las variables analizadas.", puntosOne: "", puntosTwo: "", archivo:"", formato:""},
    { clasificacion: "1 Cuenta Pública conforme a LFyRC", puntosOne: "6", puntosTwo: "0", archivo:"", formato:""},
    { clasificacion: "1. La documentación presentada cumple con los requisitos de transparencia y veracidad exigidos por la LFyRC y LGCG.", puntosOne: "1", puntosTwo: "0", archivo:"", formato:""},
    { clasificacion: "2. La cuenta pública incluye todos los elementos requeridos por la ley, como estados financieros, presupuestales y programáticos como lo indica la normativa vigente.", puntosOne: "1", puntosTwo: "0", archivo:"", formato:""},
    { clasificacion: "3. La cuenta pública está libre de omisiones significativas o irregularidades que puedan afectar su integridad y fiabilidad.", puntosOne: "4", puntosTwo: "0", archivo:"", formato:""},
    { clasificacion: "Conciliación de inventarios. Art. 27 Pfo. Primero LGCG", puntosOne: "0.2", puntosTwo: "0", archivo:"", formato:""},
    { clasificacion: "Modificaciones presupuestales. Art. 2 Pfo. Segundo LPYRHBCS", puntosOne: "0.4", puntosTwo: "0", archivo:"", formato:""},
    { clasificacion: "Manual de administración de remuneraciones, vigente y autorizado. Art. 21 Fr. VIl Lineamientos Cuenta", puntosOne: "1.6", puntosTwo: "0", archivo:"", formato:""},
    { clasificacion: "Conciliaciones bancarias", puntosOne: "1.6", puntosTwo: "0", archivo:"", formato:""},
    { clasificacion: "Relación de proveedores. Art. 9 Fr. V, inciso L) Lineamientos Cuenta Pública", puntosOne: "0.2", puntosTwo: "0", archivo:"", formato:""},
    { clasificacion: "Sistema de Contabilidad Completo (SEVAC) (Anual)", puntosOne: "7", puntosTwo: "4.55", archivo:"", formato:""},
    { clasificacion: "3 Comites de Adquisiciones Instalados", puntosOne: "6", puntosTwo: "6", archivo:"", formato:""},
    { clasificacion: "1. Cumplir con el correcto establecimiento del Comité como lo menciona el Art. 28 y todas sus fracciones de la Ley de Adquisiciones, Arrendamiento y Servicios del Sector Publico de BCS.", puntosOne: "1", puntosTwo: "1", archivo:"", formato:""},
    { clasificacion: "2. Actas de sesiones por lo menos 1 vez al año. Art. 21 Fr. II Reglamento Ley de Adq. Y Arrend. BCS", puntosOne: "1", puntosTwo: "1", archivo:"", formato:""},
    { clasificacion: "3. Programa Anual de adquisiciones. Art. 24 Ley de Adq. Y Arrend BCS", puntosOne: "4", puntosTwo: "4", archivo:"", formato:""},
    { clasificacion: "4 Obra Pública", puntosOne: "6", puntosTwo: "2.5", archivo:"", formato:""},
    { clasificacion: "1. Programa Anual de Obras Públicas aprobado.", puntosOne: "2.5", puntosTwo: "0", archivo:"", formato:""},
    { clasificacion: "2. Expedientes unitarios debidamente integrado.", puntosOne: "1", puntosTwo: "0", archivo:"", formato:""},
    { clasificacion: "3. Obras pagadas NO ejecutadas.", puntosOne: "2.5", puntosTwo: "2.5", archivo:"", formato:""},
    { clasificacion: "5 Cumplimiento de la Ley de Adquisiciones y Servicios", puntosOne: "6", puntosTwo: "2", archivo:"", formato:""},
    { clasificacion: "Procedimiento de Adquisicióncon evidencias", puntosOne: "2", puntosTwo: "0", archivo:"", formato:""},
    { clasificacion: "Expediente Técnico de la Adquisicióncon evidencia", puntosOne: "2", puntosTwo: "0", archivo:"", formato:""},
    { clasificacion: "Techo presupuestal", puntosOne: "2", puntosTwo: "2", archivo:"", formato:""},
    { clasificacion: "1. Reincidencia en: </br>", puntosOne: "", puntosTwo: "", archivo:"", formato:""},
    { clasificacion: "Sistema contable armonizado", puntosOne: "1", puntosTwo: "0", archivo:"", formato:""},
    { clasificacion: "Programa anual de adquisiciones, arrendamiento y servicios", puntosOne: "2", puntosTwo: "2", archivo:"", formato:""},
    { clasificacion: "Manual de remuneraciones y tabulador de sueldos", puntosOne: "3", puntosTwo: "0", archivo:"", formato:""},
    { clasificacion: "Procedimientos de contratacion justificando la excepcion a licitación pública", puntosOne: "1", puntosTwo: "0", archivo:"", formato:""},
    { clasificacion: "Levantamiento fisico del inventario de bienes muebles e inmuebles", puntosOne: "1", puntosTwo: "0", archivo:"", formato:""},
    { clasificacion: "NOTA: Si el Ente reincide en algun punto no mencionado se podra evaluar en un comité tecnico, integrado por la Auditoria Superior BCS, Comisión de Vigilancia y la Unidad de Evaluación y Control.", puntosOne: "", puntosTwo: "" , archivo:"", formato:""},
    { clasificacion: "7 % de Cantidad Observaciones Solventadas", puntosOne: "15", puntosTwo: "4.79", archivo:"", formato:""},
    { clasificacion: "1. Porcentaje que resulte de dividir la cantidad de observaciones solventadas entre el total de observaciones fincadas. (proporción)", puntosOne: "15", puntosTwo: 4.8, archivo:"", formato:""},
    { clasificacion: "8 % de Importe de Observaciones Solventadas", puntosOne: "35", puntosTwo: "10.01", archivo:"", formato:""},
    { clasificacion: "Porcentaje que resulte de dividir el importe solventado entre el total del importe fincado. (proporción)", puntosOne: "", puntosTwo: "", archivo:"", formato:""},
    { clasificacion: "INGRESO", puntosOne: "5", puntosTwo: "5", archivo:"", formato:""},
    { clasificacion: "EGRESO", puntosOne: "30", puntosTwo: "5.01", archivo:"", formato:""},
    { clasificacion: "VARIABLES DE CONTROL Y TRANSPARENCIA. Este criterio, pretende analizar el nivel de control y transparencia del ente, con la finalidad de ver el cumplimiento tanto de la LFyRC como de Contabilidad Gubernamental.", puntosOne: "", puntosTwo: "", archivo:"", formato:""},
    { clasificacion: "9 Ley de Disciplina Financiera", puntosOne: "3", puntosTwo: "3", archivo:"", formato:""},
    { clasificacion: "1. La información financiera esta presentada de acuerdo a los criterios de disciplina finaciera, de manera completa en su portal de internet.", puntosOne: "", puntosTwo: "", archivo:"", formato:""},
    { clasificacion: "1er Trimestre", puntosOne: "0.75", puntosTwo: "0.75", archivo:"", formato:""},
    { clasificacion: "2do Trimestre", puntosOne: "0.75", puntosTwo: "0.75", archivo:"", formato:""},
    { clasificacion: "3er Trimestre", puntosOne: "0.75", puntosTwo: "0.75", archivo:"", formato:""},
    { clasificacion: "4to Trimestre", puntosOne: "0.75", puntosTwo: "0.75", archivo:"", formato:""},
    { clasificacion: "10 Información de Cuenta Pública en Portales de internet", puntosOne: "3", puntosTwo: "3", archivo:"", formato:""},
    { clasificacion: "1. La información financiera esta de manera completa en su portal de internet, por lo menos trimestralmente, estan obligados a la publicación trimestralmente.", puntosOne: "", puntosTwo: "", archivo:"", formato:""},
    { clasificacion: "1er Trimestre", puntosOne: "0.75", puntosTwo: "0.75", archivo:"", formato:""},
    { clasificacion: "2do Trimestre", puntosOne: "0.75", puntosTwo: "0.75", archivo:"", formato:""},
    { clasificacion: "3er Trimestre", puntosOne: "0.75", puntosTwo: "0.75", archivo:"", formato:""},
    { clasificacion: "4to Trimestre", puntosOne: "0.75", puntosTwo: "0.75", archivo:"", formato:""},
    { clasificacion: "VARIABLES DE RENDICION DE CUENTAS. Este criterio, pretender medir el nivel de cumplimiento de las obligaciones de entrega de información en tiempo, entre más cercano a 25 puntos, es mayor el cumplimiento de los tiempos obligados.", puntosOne: "", puntosTwo: "", archivo:"", formato:""},
    { clasificacion: "11 Presentación de Informes Mensuales en tiempo", puntosOne: "3", puntosTwo: "0", archivo:"", formato:""},
    { clasificacion: "1. Que esten presentados los 12 informes mensuales del año. (0.5 mensual) (De acuerdo a la Ley de Fiscalización y Rendición de Cuentas y Convenio SIRET)", puntosOne: "", puntosTwo: "", archivo:"", formato:""},
    { clasificacion: "Enero", puntosOne: "0.25", puntosTwo: "0", archivo:"", formato:""},
    { clasificacion: "Febrero", puntosOne: "0.25", puntosTwo: "0", archivo:"", formato:""},
    { clasificacion: "Marzo", puntosOne: "0.25", puntosTwo: "0", archivo:"", formato:""},
    { clasificacion: "Abril", puntosOne: "0.25", puntosTwo: "0", archivo:"", formato:""},
    { clasificacion: "Mayo", puntosOne: "0.25", puntosTwo: "0", archivo:"", formato:""},
    { clasificacion: "Junio", puntosOne: "0.25", puntosTwo: "0", archivo:"", formato:""},
    { clasificacion: "Julio", puntosOne: "0.25", puntosTwo: "0", archivo:"", formato:""},
    { clasificacion: "Agosto", puntosOne: "0.25", puntosTwo: "0", archivo:"", formato:""},
    { clasificacion: "Septiembre", puntosOne: "0.25", puntosTwo: "0", archivo:"", formato:""},
    { clasificacion: "Octubre", puntosOne: "0.25", puntosTwo: "0", archivo:"", formato:""},
    { clasificacion: "Noviembre", puntosOne: "0.25", puntosTwo: "0", archivo:"", formato:""},
    { clasificacion: "Diciembre", puntosOne: "0.25", puntosTwo: "0", archivo:"", formato:""}
];

export default data;